name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Type check shared package
        run: npm run -w @launchpad/shared build

      - name: Build frontend
        run: npm run -w @launchpad/frontend build

      - name: Type check worker
        run: npm run -w @launchpad/worker typecheck

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run grader tests
        working-directory: apps/grader
        run: mvn -B test
