name: CI

on:
  pull_request:
    branches: [ "main", "dev" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      node-cache: ${{ steps.cache-node.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm ci (workspaces)
        run: npm ci

  frontend:
    name: Frontend build + lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm ci (workspaces)
        run: npm ci
      - name: Build
        run: npm run -w @launchpad/frontend build
      - name: Lint
        run: npm run -w @launchpad/frontend lint

  worker:
    name: Worker build + wrangler types
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: npm ci (workspaces)
        run: npm ci
      - name: Build
        run: npm run -w @parallel/worker build
      - name: Wrangler types check
        run: npx wrangler types -c infra/wrangler.toml

  grader:
    name: Grader tests (Maven)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Test
        working-directory: apps/grader
        run: mvn -B -DskipTests=false test
      - name: Upload surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grader-test-reports
          path: |
            apps/grader/target/surefire-reports
            apps/grader/target/failsafe-reports
          if-no-files-found: ignore
